name: Victor - Neuro-sama simulator in GitHub Actions
description: A GitHub Action that allows you to use Neuro-sama simulators in GitHub Actions runs.
author: KTrain5169

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  simulator:
    description: "Which tool to use to simulate Neuro-sama. Currently supported: Randy, Jippity"
    required: true
  #version:
    #description: "The version of the simulator to use. Does not work with Randy."
    #required: true
  deps-command:
    description: "The command to install dependencies for your game."
    required: false
  run-command:
    description: "The command to start your game."
    required: true
  actions-count:
    description: "The number of actions to observe."
    required: true

  # The following still need to be accessed (it's not functional yet)
  randy-packets:
    description: "[Randy] The file to the JSON path for packets to send to Randy."
    required: false
  jippity-api-key:
    description: "[Jippity] Your OpenAI API key (used to make Jippity function). This is not logged anywhere."
    required: false
  jippity-ai-model:
    description: "[Jippity] The OpenAI model to use. Must support tools (formerly functions)."
    required: false
    default: "gpt-4o-mini"

# Define your outputs here.
outputs:
  observed_message_count:
    description: "The observed amount of messages from the simulator."

runs:
  using: node20
  main: dist/index.js
